package promote

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

func RenderBottleReview(d BottleDraft) ([]byte, error) {
	var b bytes.Buffer
	services := bottleDraftServices(d)

	fmt.Fprintln(&b, "# Generated Bottle Draft Review")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "This file was generated by Raind Promote for the container-to-bottle workflow.")
	fmt.Fprintln(&b, "The generated bottle.yaml is a reviewable draft, not production configuration.")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Source")
	fmt.Fprintln(&b)
	if strings.TrimSpace(d.SourceContainer) != "" {
		fmt.Fprintf(&b, "- Source container(s): `%s`\n", d.SourceContainer)
	} else {
		fmt.Fprintln(&b, "- Source container(s): unknown")
	}
	fmt.Fprintf(&b, "- Bottle name: `%s`\n", valueOrUnknown(d.BottleName))
	fmt.Fprintf(&b, "- Services generated: %d\n", len(services))
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Generated")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "- `bottle.yaml` service draft")
	if len(d.Policies) > 0 {
		fmt.Fprintf(&b, "- %d security policy draft(s) copied from running Raind policy state\n", len(d.Policies))
	}
	fmt.Fprintln(&b, "- `REVIEW_BOTTLE.md` review report")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "## Observed from runtime state")
	fmt.Fprintln(&b)
	for _, svc := range services {
		renderServiceReview(&b, svc)
	}
	if len(d.Policies) > 0 {
		fmt.Fprintln(&b, "### Security policy drafts")
		fmt.Fprintln(&b)
		for _, policy := range d.Policies {
			fmt.Fprintf(&b, "- `%s` -> `%s`", valueOrUnknown(policy.Source), valueOrUnknown(policy.Destination))
			parts := []string{}
			if policy.Type != "" {
				parts = append(parts, "type `"+policy.Type+"`")
			}
			if policy.Protocol != "" {
				parts = append(parts, "protocol `"+policy.Protocol+"`")
			}
			if policy.DestPort != 0 {
				parts = append(parts, fmt.Sprintf("destination port `%d`", policy.DestPort))
			}
			if len(parts) > 0 {
				fmt.Fprintf(&b, " (%s)", strings.Join(parts, ", "))
			}
			fmt.Fprintln(&b)
		}
		fmt.Fprintln(&b)
	}

	fmt.Fprintln(&b, "## Needs review")
	fmt.Fprintln(&b)
	renderReviewTodos(&b, d, services)

	if len(d.Warnings) > 0 {
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "## Warnings")
		fmt.Fprintln(&b)
		for _, w := range d.Warnings {
			fmt.Fprintf(&b, "- `%s`: %s\n", w.Code, w.Message)
		}
	}

	return b.Bytes(), nil
}

func renderServiceReview(b *bytes.Buffer, svc ServiceDraft) {
	name := svc.Name
	if name == "" {
		name = "app"
	}
	fmt.Fprintf(b, "### Service `%s`\n", name)
	fmt.Fprintln(b)
	fmt.Fprintf(b, "- Image: `%s`\n", valueOrUnknown(svc.Image))
	if len(svc.Command) > 0 {
		fmt.Fprintf(b, "- Command: `%s`\n", strings.Join(svc.Command, " "))
	} else {
		fmt.Fprintln(b, "- Command: inherited from image")
	}

	nonSecretEnv, secretEnv := splitEnvKeys(svc.Env)
	fmt.Fprintf(b, "- Environment variables: %d non-secret candidate(s)", len(nonSecretEnv))
	if len(secretEnv) > 0 {
		fmt.Fprintf(b, ", %d secret candidate(s) redacted", len(secretEnv))
	}
	fmt.Fprintln(b)
	if len(nonSecretEnv) > 0 {
		fmt.Fprintf(b, "  - Config env candidates: `%s`\n", strings.Join(nonSecretEnv, "`, `"))
	}
	if len(secretEnv) > 0 {
		fmt.Fprintf(b, "  - Secret candidates: `%s`\n", strings.Join(secretEnv, "`, `"))
	}

	if len(svc.Ports) > 0 {
		ports := make([]string, 0, len(svc.Ports))
		for _, p := range svc.Ports {
			ports = append(ports, renderPort(p))
		}
		fmt.Fprintf(b, "- Ports: `%s`\n", strings.Join(ports, "`, `"))
	} else {
		fmt.Fprintln(b, "- Ports: none observed")
	}

	if len(svc.Mounts) > 0 {
		mounts := make([]string, 0, len(svc.Mounts))
		for _, m := range svc.Mounts {
			mounts = append(mounts, renderMount(m))
		}
		fmt.Fprintf(b, "- Mounts: `%s`\n", strings.Join(mounts, "`, `"))
	} else {
		fmt.Fprintln(b, "- Mounts: none observed")
	}

	if len(svc.DependsOn) > 0 {
		fmt.Fprintf(b, "- Inferred dependencies: `%s`\n", strings.Join(svc.DependsOn, "`, `"))
	} else {
		fmt.Fprintln(b, "- Inferred dependencies: none")
	}
	if svc.Tty {
		fmt.Fprintln(b, "- TTY: enabled")
	}
	fmt.Fprintln(b)
}

func renderReviewTodos(b *bytes.Buffer, d BottleDraft, services []ServiceDraft) {
	secretKeys := []string{}
	absoluteMounts := []string{}
	for _, svc := range services {
		_, secretEnv := splitEnvKeys(svc.Env)
		for _, key := range secretEnv {
			secretKeys = append(secretKeys, svc.Name+"."+key)
		}
		for _, m := range svc.Mounts {
			if strings.HasPrefix(m.Source, "/") {
				name := svc.Name
				if name == "" {
					name = "app"
				}
				absoluteMounts = append(absoluteMounts, name+":"+m.Source+" -> "+m.Destination)
			}
		}
	}
	sort.Strings(secretKeys)
	sort.Strings(absoluteMounts)

	fmt.Fprintln(b, "- Confirm service names, bottle name, image references, command, and args.")
	fmt.Fprintln(b, "- Review non-secret environment variables before committing the generated bottle.yaml.")
	if len(secretKeys) > 0 {
		fmt.Fprintf(b, "- Replace or externalize redacted secret candidates: `%s`.\n", strings.Join(secretKeys, "`, `"))
	} else {
		fmt.Fprintln(b, "- Confirm that no sensitive environment variables were missed by key-name inference.")
	}
	fmt.Fprintln(b, "- Confirm published ports and protocols match the intended local Bottle workflow.")
	if len(absoluteMounts) > 0 {
		fmt.Fprintf(b, "- Review host-specific absolute mounts: `%s`.\n", strings.Join(absoluteMounts, "`, `"))
	} else {
		fmt.Fprintln(b, "- Add persistent mounts if the application needs local state.")
	}
	fmt.Fprintln(b, "- Review inferred dependencies before relying on startup order.")
	if len(d.Policies) > 0 {
		fmt.Fprintln(b, "- Review copied security policy drafts; they reflect current Raind policy state and may need narrowing.")
	} else {
		fmt.Fprintln(b, "- Add bottle policies manually if the services need explicit east-west network boundaries.")
	}
}

func splitEnvKeys(envs []EnvVar) ([]string, []string) {
	nonSecret := []string{}
	secret := []string{}
	for _, env := range envs {
		key := strings.TrimSpace(env.Key)
		if key == "" {
			continue
		}
		if env.Sensitive {
			secret = append(secret, key)
		} else {
			nonSecret = append(nonSecret, key)
		}
	}
	sort.Strings(nonSecret)
	sort.Strings(secret)
	return nonSecret, secret
}

func valueOrUnknown(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "unknown"
	}
	return value
}
