package promote

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
)

func RenderBottlefile(d BottleDraft) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Generated by Raind Promote from %s.\n", d.SourceContainer)
	fmt.Fprintln(&b, "# This bottle.yaml is a reviewable draft, not production configuration.")
	fmt.Fprintln(&b, "# Review env, mounts, ports, dependencies, and secret candidates before sharing.")
	if len(d.Warnings) > 0 {
		fmt.Fprintln(&b, "#")
		fmt.Fprintln(&b, "# Warnings:")
		for _, w := range d.Warnings {
			fmt.Fprintf(&b, "# - %s: %s\n", w.Code, w.Message)
		}
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "bottle:")
	fmt.Fprintf(&b, "  name: %s\n", quoteYAMLString(d.BottleName))
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "services:")
	for _, svc := range bottleDraftServices(d) {
		renderService(&b, svc)
	}
	if len(d.Policies) > 0 {
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "policies:")
		for _, policy := range d.Policies {
			renderPolicy(&b, policy)
		}
	}
	return b.Bytes(), nil
}

func RenderComposefile(d BottleDraft) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Generated by Raind Promote from %s.\n", d.SourceContainer)
	fmt.Fprintln(&b, "# This compose.yaml is a reviewable draft, not production configuration.")
	fmt.Fprintln(&b, "# Review env, mounts, ports, and dependencies before sharing.")
	if len(d.Warnings) > 0 {
		fmt.Fprintln(&b, "#")
		fmt.Fprintln(&b, "# Warnings:")
		for _, w := range d.Warnings {
			fmt.Fprintf(&b, "# - %s: %s\n", w.Code, w.Message)
		}
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "services:")
	for _, svc := range bottleDraftServices(d) {
		renderService(&b, svc)
	}
	return b.Bytes(), nil
}

func bottleDraftServices(d BottleDraft) []ServiceDraft {
	if len(d.Services) > 0 {
		return d.Services
	}
	return []ServiceDraft{{
		Name:    d.ServiceName,
		Image:   d.Image,
		Command: d.Command,
		Env:     d.Env,
		Ports:   d.Ports,
		Mounts:  d.Mounts,
		Network: d.Network,
		Tty:     d.Tty,
	}}
}

func renderService(b *bytes.Buffer, svc ServiceDraft) {
	name := svc.Name
	if name == "" {
		name = "app"
	}
	fmt.Fprintf(b, "  %s:\n", name)
	if svc.Image != "" {
		fmt.Fprintf(b, "    image: %s\n", quoteYAMLString(svc.Image))
	}
	if len(svc.Command) > 0 {
		fmt.Fprintln(b, "    command:")
		for _, arg := range svc.Command {
			fmt.Fprintf(b, "      - %s\n", quoteYAMLString(arg))
		}
	}
	if len(svc.Env) > 0 {
		nonSecretEnv := 0
		for _, env := range svc.Env {
			if env.Sensitive {
				fmt.Fprintf(b, "    # TODO: secret candidate redacted from container env: %s\n", env.Key)
				fmt.Fprintf(b, "    # env example: %s=<redacted>\n", env.Key)
				continue
			}
			nonSecretEnv++
		}
		if nonSecretEnv > 0 {
			fmt.Fprintln(b, "    env:")
			for _, env := range svc.Env {
				if env.Sensitive {
					continue
				}
				fmt.Fprintf(b, "      - %s\n", quoteYAMLString(env.Key+"="+env.Value))
			}
		}
	}
	if len(svc.Ports) > 0 {
		fmt.Fprintln(b, "    ports:")
		for _, p := range svc.Ports {
			fmt.Fprintf(b, "      - %s\n", quoteYAMLString(renderPort(p)))
		}
	}
	if len(svc.Mounts) > 0 {
		fmt.Fprintln(b, "    mount:")
		for _, m := range svc.Mounts {
			fmt.Fprintf(b, "      - %s\n", quoteYAMLString(renderMount(m)))
		}
	}
	if svc.Network != "" {
		fmt.Fprintf(b, "    network: %s\n", quoteYAMLString(svc.Network))
	}
	if len(svc.DependsOn) > 0 {
		fmt.Fprintln(b, "    depends_on:")
		for _, dep := range svc.DependsOn {
			fmt.Fprintf(b, "      - %s\n", quoteYAMLString(dep))
		}
	}
	if svc.Tty {
		fmt.Fprintln(b, "    tty: true")
	}
}

func renderPort(p PortMapping) string {
	protocol := strings.ToLower(strings.TrimSpace(p.Protocol))
	if protocol == "" || protocol == "tcp" {
		return fmt.Sprintf("%d:%d", p.HostPort, p.ContainerPort)
	}
	return fmt.Sprintf("%d:%d:%s", p.HostPort, p.ContainerPort, protocol)
}

func renderMount(m MountMapping) string {
	value := m.Source + ":" + m.Destination
	if m.ReadOnly {
		value += ":ro"
	}
	return value
}

func quoteYAMLString(s string) string {
	return strconv.Quote(s)
}

func renderPolicy(b *bytes.Buffer, p PolicyDraft) {
	fmt.Fprintf(b, "  - type: %s\n", quoteYAMLString(p.Type))
	fmt.Fprintf(b, "    source: %s\n", quoteYAMLString(p.Source))
	fmt.Fprintf(b, "    destination: %s\n", quoteYAMLString(p.Destination))
	if p.Protocol != "" {
		fmt.Fprintf(b, "    protocol: %s\n", quoteYAMLString(p.Protocol))
	}
	if p.DestPort != 0 {
		fmt.Fprintf(b, "    dest_port: %d\n", p.DestPort)
	}
	if p.Comment != "" {
		fmt.Fprintf(b, "    comment: %s\n", quoteYAMLString(p.Comment))
	}
}
