package promote

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
)

func RenderBottlefile(d BottleDraft) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Generated by Raind Promote from %s.\n", d.SourceContainer)
	fmt.Fprintln(&b, "# This Dripfile is a reviewable draft, not production configuration.")
	fmt.Fprintln(&b, "# Review env, mounts, ports, and secret candidates before sharing.")
	if len(d.Warnings) > 0 {
		fmt.Fprintln(&b, "#")
		fmt.Fprintln(&b, "# Warnings:")
		for _, w := range d.Warnings {
			fmt.Fprintf(&b, "# - %s: %s\n", w.Code, w.Message)
		}
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "bottle:")
	fmt.Fprintf(&b, "  name: %s\n", quoteYAMLString(d.BottleName))
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "services:")
	fmt.Fprintf(&b, "  %s:\n", d.ServiceName)
	if d.Image != "" {
		fmt.Fprintf(&b, "    image: %s\n", quoteYAMLString(d.Image))
	}
	if len(d.Command) > 0 {
		fmt.Fprintln(&b, "    command:")
		for _, arg := range d.Command {
			fmt.Fprintf(&b, "      - %s\n", quoteYAMLString(arg))
		}
	}
	if len(d.Env) > 0 {
		nonSecretEnv := 0
		for _, env := range d.Env {
			if env.Sensitive {
				fmt.Fprintf(&b, "    # TODO: secret candidate redacted from container env: %s\n", env.Key)
				fmt.Fprintf(&b, "    # env example: %s=<redacted>\n", env.Key)
				continue
			}
			nonSecretEnv++
		}
		if nonSecretEnv > 0 {
			fmt.Fprintln(&b, "    env:")
			for _, env := range d.Env {
				if env.Sensitive {
					continue
				}
				fmt.Fprintf(&b, "      - %s\n", quoteYAMLString(env.Key+"="+env.Value))
			}
		}
	}
	if len(d.Ports) > 0 {
		fmt.Fprintln(&b, "    ports:")
		for _, p := range d.Ports {
			fmt.Fprintf(&b, "      - %s\n", quoteYAMLString(renderPort(p)))
		}
	}
	if len(d.Mounts) > 0 {
		fmt.Fprintln(&b, "    mount:")
		for _, m := range d.Mounts {
			fmt.Fprintf(&b, "      - %s\n", quoteYAMLString(renderMount(m)))
		}
	}
	if d.Network != "" {
		fmt.Fprintf(&b, "    network: %s\n", quoteYAMLString(d.Network))
	}
	if d.Tty {
		fmt.Fprintln(&b, "    tty: true")
	}
	return b.Bytes(), nil
}

func renderPort(p PortMapping) string {
	protocol := strings.ToLower(strings.TrimSpace(p.Protocol))
	if protocol == "" || protocol == "tcp" {
		return fmt.Sprintf("%d:%d", p.HostPort, p.ContainerPort)
	}
	return fmt.Sprintf("%d:%d:%s", p.HostPort, p.ContainerPort, protocol)
}

func renderMount(m MountMapping) string {
	value := m.Source + ":" + m.Destination
	if m.ReadOnly {
		value += ":ro"
	}
	return value
}

func quoteYAMLString(s string) string {
	return strconv.Quote(s)
}
