package utils

const (
	RootDir          = "/etc/raind"
	AuditLogDir      = "/etc/raind/log/"
	ContainerRootDir = "/etc/raind/container"
	ImageRootDir     = "/etc/raind/image"
	LayerRootDir     = "/etc/raind/image/layers"
	VarLogDir        = "/var/log/raind"

	StoreDir          = "/etc/raind/store"
	StoreContainerDir = "/etc/raind/store/container"
	StoreImageDir     = "/etc/raind/store/image"
	StoreNetworkDir   = "/etc/raind/store/network"
	StoreResourceDir  = "/etc/raind/store/resource"

	IpamStorePath = "/etc/raind/store/network/ipam.json"
	CsmStorePath  = "/etc/raind/store/container/csm.json"
	PsmStorePath  = "/etc/raind/store/resource/pod/psm.json"
	IlmStorePath  = "/etc/raind/store/image/ilm.json"
	SsmStorePath  = "/etc/raind/store/resource/service/ssm.json"
	IsmStorePath  = "/etc/raind/store/resource/ingress/ism.json"
	CfmStorePath  = "/etc/raind/store/resource/configmap/cfm.json"
	SecStorePath  = "/etc/raind/store/resource/secret/sec.json"
	NpmStorePath  = "/etc/raind/store/network/npm.json"
	BsmStorePath  = "/etc/raind/store/container/bsm.json"
	NsmStorePath  = "/etc/raind/store/resource/namespace/nsm.json"

	OldIpamStorePath = "/etc/raind/store/ipam.json"
	OldCsmStorePath  = "/etc/raind/store/csm.json"
	OldPsmStorePath  = "/etc/raind/store/psm.json"
	OldIlmStorePath  = "/etc/raind/store/ilm.json"
	OldSsmStorePath  = "/etc/raind/store/ssm.json"
	OldIsmStorePath  = "/etc/raind/store/ism.json"
	OldCfmStorePath  = "/etc/raind/store/cfm.json"
	OldSecStorePath  = "/etc/raind/store/sec.json"
	OldNpmStorePath  = "/etc/raind/store/npm.json"
	OldBsmStorePath  = "/etc/raind/store/bsm.json"
	OldNsmStorePath  = "/etc/raind/store/nsm.json"

	CgroupRuntimeDir         = "/sys/fs/cgroup/raind"
	CgroupSubtreeControlPath = "/sys/fs/cgroup/raind/cgroup.subtree_control"

	CertDir                 = "/etc/raind/cert"
	CliCertDir              = "/etc/raind/cli"
	IngressCertDir          = "/etc/raind/ingress/cert"
	PublicCertPath          = "/etc/raind/cert/raind.crt"
	PrivateKeyPath          = "/etc/raind/cert/raind.key"
	CliPublicCertPath       = "/etc/raind/cli/ca.crt"
	CliClientCertPath       = "/etc/raind/cli/client.crt"
	CliClientKeyPath        = "/etc/raind/cli/client.key"
	ClientIssuerCACertPath  = "/etc/raind/cert/raindClientCA.crt"
	ClientIssuerCAKeyPath   = "/etc/raind/cert/raindClientCA.key"
	ClientCertPath          = "/etc/raind/cert/raindClient.crt"
	ClientKeyPath           = "/etc/raind/cert/raindClient.key"
	HookClientCertPath      = "/etc/raind/cert/raindHookClient.crt"
	HookClientKeyPath       = "/etc/raind/cert/raindHookClient.key"
	IngressIssuerCACertPath = "/etc/raind/ingress/cert/raindIngressCA.crt"
	IngressIssuerCAKeyPath  = "/etc/raind/ingress/cert/raindIngressCA.key"

	UlogPath        = "/var/log/ulog/raind.jsonl"
	AuditLogPath    = "/var/log/raind/raind_audit.jsonl"
	EnrichedLogPath = "/var/log/raind/raind_netflow.jsonl"
	DnsLogPath      = "/var/log/raind/raind_dns.jsonl"
	MetricsLogPath  = "/var/log/raind/raind_metrics.jsonl"

	RaindGroupName = "raind"

	PodInfraImage               = "registry.k8s.io/pause:3.9"
	PodInfraContainerNamePrefix = "condenser-pod-infra-"
)
