// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/bottle": {
            "get": {
                "description": "list bottles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bottles"
                ],
                "summary": "list bottles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "register a bottle from yaml spec",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bottles"
                ],
                "summary": "register a bottle",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/bottle/{bottleId}": {
            "get": {
                "description": "get bottle detail by id or name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bottles"
                ],
                "summary": "get bottle detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bottle ID or Name",
                        "name": "bottleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/bottle/{bottleId}/actions/{action}": {
            "post": {
                "description": "start/stop/remove bottle",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bottles"
                ],
                "summary": "perform bottle action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bottle ID or Name",
                        "name": "bottleId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Action",
                        "name": "action",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers": {
            "get": {
                "description": "get all container list",
                "tags": [
                    "containers"
                ],
                "summary": "get container list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Create a container",
                "parameters": [
                    {
                        "description": "Container Spec",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/container.CreateContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/stats": {
            "get": {
                "description": "list container stats",
                "tags": [
                    "containers"
                ],
                "summary": "list container stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}": {
            "get": {
                "description": "get an exitsting container info",
                "tags": [
                    "containers"
                ],
                "summary": "get container info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/delete": {
            "delete": {
                "description": "delete an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "delete a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/exec": {
            "post": {
                "description": "execute command inside an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "exec a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Execute Options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/container.ExecContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/start": {
            "post": {
                "description": "start an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "start a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Start Options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/container.StartContainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/actions/stop": {
            "post": {
                "description": "stop an exitsting container",
                "tags": [
                    "containers"
                ],
                "summary": "stop a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/log": {
            "get": {
                "description": "get container log",
                "tags": [
                    "containers"
                ],
                "summary": "get container log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/logpath": {
            "get": {
                "description": "get container log path",
                "tags": [
                    "containers"
                ],
                "summary": "get container log path",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/containers/{containerId}/stats": {
            "get": {
                "description": "get container stats",
                "tags": [
                    "containers"
                ],
                "summary": "get container stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Container ID",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/hooks/droplet": {
            "post": {
                "description": "apply hook from droplet",
                "tags": [
                    "hooks"
                ],
                "summary": "apply hook",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/images": {
            "get": {
                "description": "get image list in local storage",
                "tags": [
                    "image"
                ],
                "summary": "get image list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "pull image from registry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "pull image",
                "parameters": [
                    {
                        "description": "Target Image",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/image.PullImageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove image from local",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "remove image",
                "parameters": [
                    {
                        "description": "Target Image",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/image.RemoveImageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/images/build": {
            "post": {
                "description": "build image from Dripfile-like archive (tar)",
                "consumes": [
                    "application/x-tar"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "build image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target image tag (e.g. myapp:latest)",
                        "name": "tag",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Dripfile path in context (default: Dripfile)",
                        "name": "dripfile",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Bridge interface (default: raind0)",
                        "name": "network",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/images/fs": {
            "get": {
                "description": "get image filesystem usage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "get image fs info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target Image",
                        "name": "image",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/images/status": {
            "get": {
                "description": "get image status details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "get image status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target Image",
                        "name": "image",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/networks": {
            "get": {
                "description": "get bridge list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Network"
                ],
                "summary": "get bridge list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create new bridge",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Network"
                ],
                "summary": "create bridge",
                "parameters": [
                    {
                        "description": "Bridge Information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/network.CreateBridgeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/networks/{bridge}/actions/delete": {
            "delete": {
                "description": "delete new bridge",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Network"
                ],
                "summary": "delete bridge",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/pods": {
            "get": {
                "description": "list pod sandbox",
                "tags": [
                    "pods"
                ],
                "summary": "list pods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create a pod sandbox (no container start)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pods"
                ],
                "summary": "create pod sandbox",
                "parameters": [
                    {
                        "description": "Pod Spec",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pod.CreatePodRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/pods/{podId}": {
            "get": {
                "description": "get pod sandbox detail",
                "tags": [
                    "pods"
                ],
                "summary": "get pod detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pod ID",
                        "name": "podId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove a pod sandbox",
                "tags": [
                    "pods"
                ],
                "summary": "remove pod sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pod ID",
                        "name": "podId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/pods/{podId}/actions/start": {
            "post": {
                "description": "start a pod sandbox",
                "tags": [
                    "pods"
                ],
                "summary": "start pod sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pod ID",
                        "name": "podId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/pods/{podId}/actions/stop": {
            "post": {
                "description": "stop a pod sandbox",
                "tags": [
                    "pods"
                ],
                "summary": "stop pod sandbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pod ID",
                        "name": "podId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies": {
            "get": {
                "description": "get policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "get policy list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain Name",
                        "name": "chainName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add new policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "Add policy",
                "parameters": [
                    {
                        "description": "policy parameter",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/policy.AddPolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/commit": {
            "post": {
                "description": "commit all policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "commit policy",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/ns/mode": {
            "post": {
                "description": "change north-south mode",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "change north-south mode",
                "parameters": [
                    {
                        "description": "mode",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/policy.ChangeNSModeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/revert": {
            "post": {
                "description": "revert policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "revert policy",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/policies/{policyId}": {
            "delete": {
                "description": "remove an existing policy",
                "tags": [
                    "Policy"
                ],
                "summary": "remove a policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/replicasets": {
            "get": {
                "description": "list replica sets",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "replicasets"
                ],
                "summary": "list replica sets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/replicasets/{replicaSetId}": {
            "get": {
                "description": "get replica set detail",
                "tags": [
                    "replicasets"
                ],
                "summary": "get replica set detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ReplicaSet ID",
                        "name": "replicaSetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove replica set",
                "tags": [
                    "replicasets"
                ],
                "summary": "remove replica set",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ReplicaSet ID",
                        "name": "replicaSetId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/replicasets/{replicaSetId}/actions/scale": {
            "post": {
                "description": "scale replica set replicas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "replicasets"
                ],
                "summary": "scale replica set",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ReplicaSet ID",
                        "name": "replicaSetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Scale Options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pod.ScaleReplicaSetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/resource/apply": {
            "post": {
                "description": "apply kubectl-compatible yaml manifest",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pods"
                ],
                "summary": "apply pod/replicaset manifest",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/resource/delete": {
            "post": {
                "description": "delete resources defined in kubectl-compatible yaml manifest",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "delete resources by manifest",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/services": {
            "get": {
                "description": "list services",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "list services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create a L4 service",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "create service",
                "parameters": [
                    {
                        "description": "Service Manifest (yaml)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        },
        "/v1/services/{serviceId}": {
            "get": {
                "description": "get service detail",
                "tags": [
                    "services"
                ],
                "summary": "get service detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "serviceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "remove service",
                "tags": [
                    "services"
                ],
                "summary": "remove service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "serviceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "container.CreateContainerRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "/bin/sh",
                        "-c",
                        "echo hello; sleep 60"
                    ]
                },
                "env": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "image": {
                    "type": "string",
                    "example": "alpine:latest"
                },
                "mount": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "/host/dir:/container/dir",
                        "/src:/dst"
                    ]
                },
                "name": {
                    "type": "string",
                    "example": "my-container"
                },
                "network": {
                    "type": "string",
                    "example": "raind0"
                },
                "podId": {
                    "type": "string",
                    "example": "pod-1234"
                },
                "port": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "8080:80",
                        "4443:443"
                    ]
                },
                "tty": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "container.ExecContainerRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "/bin/sh",
                        "-c",
                        "echo hello"
                    ]
                },
                "tty": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "container.StartContainerRequest": {
            "type": "object",
            "properties": {
                "tty": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "image.PullImageRequest": {
            "type": "object",
            "properties": {
                "arch": {
                    "type": "string",
                    "example": "arm64"
                },
                "image": {
                    "type": "string",
                    "example": "alpine:latest"
                },
                "os": {
                    "type": "string",
                    "example": "linux"
                }
            }
        },
        "image.RemoveImageRequest": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string",
                    "example": "alpine:latest"
                }
            }
        },
        "network.CreateBridgeRequest": {
            "type": "object",
            "properties": {
                "bridge": {
                    "type": "string"
                }
            }
        },
        "pod.CreatePodContainerRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "env": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "image": {
                    "type": "string"
                },
                "mount": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "port": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tty": {
                    "type": "boolean"
                }
            }
        },
        "pod.CreatePodRequest": {
            "type": "object",
            "properties": {
                "annotations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pod.CreatePodContainerRequest"
                    }
                },
                "ipcNS": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "networkNS": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "userNS": {
                    "type": "string"
                },
                "utsNS": {
                    "type": "string"
                }
            }
        },
        "pod.ScaleReplicaSetRequest": {
            "type": "object",
            "properties": {
                "replicas": {
                    "type": "integer"
                }
            }
        },
        "policy.AddPolicyRequest": {
            "type": "object",
            "properties": {
                "chain": {
                    "type": "string",
                    "example": "RAIND-EW"
                },
                "comment": {
                    "type": "string",
                    "example": "allow https traffic"
                },
                "dest": {
                    "type": "string",
                    "example": "dst-container-name"
                },
                "dport": {
                    "type": "integer",
                    "example": 443
                },
                "protocol": {
                    "type": "string",
                    "example": "tcp"
                },
                "source": {
                    "type": "string",
                    "example": "src-container-name"
                }
            }
        },
        "policy.ChangeNSModeRequest": {
            "type": "object",
            "properties": {
                "mode": {
                    "type": "string",
                    "example": "enforce"
                }
            }
        },
        "utils.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "description": "success | fail",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
